package ytdlpauth

import (
	"bufio"
	"bytes"
	"context"
	"crypto/rand"
	"crypto/sha1"
	"encoding/base64"
	"encoding/binary"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"math"
	"net"
	"net/http"
	"net/url"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"sort"
	"strconv"
	"strings"
	"time"

	"imagepadserver/internal/settings"
)

const loginURL = "https://www.youtube.com/"

type Cookie struct {
	Name     string  `json:"name"`
	Value    string  `json:"value"`
	Domain   string  `json:"domain"`
	Path     string  `json:"path"`
	Expires  float64 `json:"expires"`
	HTTPOnly bool    `json:"httpOnly"`
	Secure   bool    `json:"secure"`
}

type StatusInfo struct {
	Saved bool   `json:"saved"`
	Path  string `json:"path,omitempty"`
}

func CookieFilePath() string {
	return filepath.Join(settings.Dir(), "cookies", "yt-dlp-cookies.txt")
}

func ProfileDir() string {
	return filepath.Join(settings.Dir(), "cookies", "login-browser-profile")
}

func Status() StatusInfo {
	path := CookieFilePath()
	info, err := os.Stat(path)
	if err != nil || info.IsDir() || info.Size() == 0 {
		return StatusInfo{Saved: false}
	}
	return StatusInfo{Saved: true, Path: path}
}

func DeleteCookies() error {
	var firstErr error
	if err := os.Remove(CookieFilePath()); err != nil && !os.IsNotExist(err) {
		firstErr = err
	}
	if err := os.RemoveAll(ProfileDir()); err != nil && firstErr == nil {
		firstErr = err
	}
	return firstErr
}

func SavedCookieArgs() []string {
	status := Status()
	if !status.Saved {
		return nil
	}
	return []string{"--cookies", status.Path}
}

func WriteNetscapeCookies(path string, cookies []Cookie) error {
	if err := os.MkdirAll(filepath.Dir(path), 0700); err != nil {
		return err
	}
	sort.SliceStable(cookies, func(i, j int) bool {
		if cookies[i].Domain == cookies[j].Domain {
			return cookies[i].Name < cookies[j].Name
		}
		return cookies[i].Domain < cookies[j].Domain
	})
	var buf bytes.Buffer
	buf.WriteString("# Netscape HTTP Cookie File\n")
	buf.WriteString("# This file is generated by ImagePadServer for yt-dlp.\n\n")
	for _, c := range cookies {
		if c.Name == "" || c.Domain == "" {
			continue
		}
		domain := c.Domain
		if c.HTTPOnly && !strings.HasPrefix(domain, "#HttpOnly_") {
			domain = "#HttpOnly_" + domain
		}
		includeSubdomains := "FALSE"
		if strings.HasPrefix(c.Domain, ".") {
			includeSubdomains = "TRUE"
		}
		pathValue := c.Path
		if pathValue == "" {
			pathValue = "/"
		}
		secure := "FALSE"
		if c.Secure {
			secure = "TRUE"
		}
		expires := int64(0)
		if c.Expires > 0 && !math.IsInf(c.Expires, 0) && !math.IsNaN(c.Expires) {
			expires = int64(c.Expires)
		}
		fmt.Fprintf(&buf, "%s\t%s\t%s\t%s\t%d\t%s\t%s\n", domain, includeSubdomains, pathValue, secure, expires, c.Name, c.Value)
	}
	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, buf.Bytes(), 0600); err != nil {
		return err
	}
	return os.Rename(tmp, path)
}

func LaunchLoginAndSave(ctx context.Context) (StatusInfo, error) {
	exe, err := chromiumPath()
	if err != nil {
		return Status(), err
	}
	port, err := freePort()
	if err != nil {
		return Status(), err
	}
	if err := os.MkdirAll(ProfileDir(), 0700); err != nil {
		return Status(), err
	}
	cmd := exec.Command(exe,
		"--user-data-dir="+ProfileDir(),
		"--remote-debugging-address=127.0.0.1",
		"--remote-debugging-port="+strconv.Itoa(port),
		"--new-window",
		loginURL,
	)
	if runtime.GOOS == "windows" {
		hideWindow(cmd)
	}
	if err := cmd.Start(); err != nil {
		return Status(), err
	}
	deadlineCtx, cancel := context.WithTimeout(ctx, 5*time.Minute)
	defer cancel()
	cookies, err := waitForYouTubeCookies(deadlineCtx, port)
	if err != nil {
		return Status(), err
	}
	if err := WriteNetscapeCookies(CookieFilePath(), cookies); err != nil {
		return Status(), err
	}
	return Status(), nil
}

func waitForYouTubeCookies(ctx context.Context, port int) ([]Cookie, error) {
	ticker := time.NewTicker(2 * time.Second)
	defer ticker.Stop()
	var pageWS string
	for {
		var err error
		if pageWS == "" {
			pageWS, err = pageWebSocketURL(ctx, port)
			if err != nil {
				select {
				case <-ctx.Done():
					return nil, errors.New("ログイン用ブラウザの起動を確認できませんでした")
				case <-ticker.C:
					continue
				}
			}
		}
		cookies, err := readCookiesFromPage(ctx, pageWS)
		if err == nil && hasYouTubeLoginCookie(cookies) {
			return filterYouTubeCookies(cookies), nil
		}
		select {
		case <-ctx.Done():
			return nil, errors.New("YouTubeログインCookieを取得できませんでした。ログイン後にもう一度実行してください")
		case <-ticker.C:
		}
	}
}

func hasYouTubeLoginCookie(cookies []Cookie) bool {
	for _, c := range cookies {
		if !strings.Contains(c.Domain, "youtube.com") {
			continue
		}
		switch c.Name {
		case "LOGIN_INFO", "SID", "HSID", "SSID", "APISID", "SAPISID", "__Secure-1PSID", "__Secure-3PSID":
			return true
		}
	}
	return false
}

func filterYouTubeCookies(cookies []Cookie) []Cookie {
	out := make([]Cookie, 0, len(cookies))
	for _, c := range cookies {
		if strings.Contains(c.Domain, "youtube.com") || strings.Contains(c.Domain, "google.com") {
			out = append(out, c)
		}
	}
	return out
}

func readCookiesFromPage(ctx context.Context, pageWS string) ([]Cookie, error) {
	var response struct {
		Result struct {
			Cookies []Cookie `json:"cookies"`
		} `json:"result"`
		Error *struct {
			Message string `json:"message"`
		} `json:"error,omitempty"`
	}
	if err := callWebSocketJSON(ctx, pageWS, map[string]interface{}{
		"id":     1,
		"method": "Network.getAllCookies",
	}, &response); err != nil {
		return nil, err
	}
	if response.Error != nil {
		return nil, errors.New(response.Error.Message)
	}
	return response.Result.Cookies, nil
}

func pageWebSocketURL(ctx context.Context, port int) (string, error) {
	client := &http.Client{Timeout: 3 * time.Second}
	listURL := fmt.Sprintf("http://127.0.0.1:%d/json/list", port)
	req, _ := http.NewRequestWithContext(ctx, http.MethodGet, listURL, nil)
	resp, err := client.Do(req)
	if err == nil {
		defer resp.Body.Close()
		var pages []struct {
			URL                  string `json:"url"`
			Type                 string `json:"type"`
			WebSocketDebuggerURL string `json:"webSocketDebuggerUrl"`
		}
		if json.NewDecoder(resp.Body).Decode(&pages) == nil {
			for _, page := range pages {
				if page.Type == "page" && strings.Contains(page.URL, "youtube.com") && page.WebSocketDebuggerURL != "" {
					return page.WebSocketDebuggerURL, nil
				}
			}
		}
	}
	newURL := fmt.Sprintf("http://127.0.0.1:%d/json/new?%s", port, url.QueryEscape(loginURL))
	req, _ = http.NewRequestWithContext(ctx, http.MethodPut, newURL, nil)
	resp, err = client.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()
	var page struct {
		WebSocketDebuggerURL string `json:"webSocketDebuggerUrl"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&page); err != nil {
		return "", err
	}
	if page.WebSocketDebuggerURL == "" {
		return "", errors.New("DevTools page websocket URL is empty")
	}
	return page.WebSocketDebuggerURL, nil
}

func callWebSocketJSON(ctx context.Context, rawURL string, request interface{}, response interface{}) error {
	u, err := url.Parse(rawURL)
	if err != nil {
		return err
	}
	conn, err := (&net.Dialer{}).DialContext(ctx, "tcp", u.Host)
	if err != nil {
		return err
	}
	defer conn.Close()
	keyBytes := make([]byte, 16)
	if _, err := rand.Read(keyBytes); err != nil {
		return err
	}
	key := base64.StdEncoding.EncodeToString(keyBytes)
	path := u.RequestURI()
	if path == "" {
		path = "/"
	}
	_, _ = fmt.Fprintf(conn, "GET %s HTTP/1.1\r\nHost: %s\r\nUpgrade: websocket\r\nConnection: Upgrade\r\nSec-WebSocket-Key: %s\r\nSec-WebSocket-Version: 13\r\n\r\n", path, u.Host, key)
	reader := bufio.NewReader(conn)
	status, err := reader.ReadString('\n')
	if err != nil {
		return err
	}
	if !strings.Contains(status, "101") {
		return fmt.Errorf("websocket upgrade failed: %s", strings.TrimSpace(status))
	}
	for {
		line, err := reader.ReadString('\n')
		if err != nil {
			return err
		}
		if strings.TrimSpace(line) == "" {
			break
		}
	}
	payload, err := json.Marshal(request)
	if err != nil {
		return err
	}
	if err := writeClientTextFrame(conn, payload); err != nil {
		return err
	}
	frame, err := readServerTextFrame(reader)
	if err != nil {
		return err
	}
	return json.Unmarshal(frame, response)
}

func writeClientTextFrame(w io.Writer, payload []byte) error {
	header := []byte{0x81}
	length := len(payload)
	switch {
	case length < 126:
		header = append(header, byte(length)|0x80)
	case length <= 65535:
		header = append(header, 126|0x80, byte(length>>8), byte(length))
	default:
		header = append(header, 127|0x80)
		var b [8]byte
		binary.BigEndian.PutUint64(b[:], uint64(length))
		header = append(header, b[:]...)
	}
	mask := make([]byte, 4)
	if _, err := rand.Read(mask); err != nil {
		return err
	}
	header = append(header, mask...)
	masked := make([]byte, len(payload))
	for i, b := range payload {
		masked[i] = b ^ mask[i%4]
	}
	if _, err := w.Write(header); err != nil {
		return err
	}
	_, err := w.Write(masked)
	return err
}

func readServerTextFrame(r *bufio.Reader) ([]byte, error) {
	var out []byte
	for {
		b0, err := r.ReadByte()
		if err != nil {
			return nil, err
		}
		b1, err := r.ReadByte()
		if err != nil {
			return nil, err
		}
		opcode := b0 & 0x0f
		length := uint64(b1 & 0x7f)
		switch length {
		case 126:
			var buf [2]byte
			if _, err := io.ReadFull(r, buf[:]); err != nil {
				return nil, err
			}
			length = uint64(binary.BigEndian.Uint16(buf[:]))
		case 127:
			var buf [8]byte
			if _, err := io.ReadFull(r, buf[:]); err != nil {
				return nil, err
			}
			length = binary.BigEndian.Uint64(buf[:])
		}
		payload := make([]byte, length)
		if _, err := io.ReadFull(r, payload); err != nil {
			return nil, err
		}
		switch opcode {
		case 0x1, 0x0:
			out = append(out, payload...)
			if b0&0x80 != 0 {
				return out, nil
			}
		case 0x8:
			return nil, errors.New("websocket closed")
		}
	}
}

func freePort() (int, error) {
	ln, err := net.Listen("tcp", "127.0.0.1:0")
	if err != nil {
		return 0, err
	}
	defer ln.Close()
	return ln.Addr().(*net.TCPAddr).Port, nil
}

func chromiumPath() (string, error) {
	if configured := os.Getenv("IMAGEPAD_CHROMIUM"); configured != "" {
		return configured, nil
	}
	candidates := chromiumCandidates()
	for _, candidate := range candidates {
		if candidate == "" {
			continue
		}
		if info, err := os.Stat(candidate); err == nil && !info.IsDir() {
			return candidate, nil
		}
	}
	for _, name := range []string{"msedge", "chrome", "chromium"} {
		if path, err := exec.LookPath(name); err == nil {
			return path, nil
		}
	}
	return "", errors.New("ChromeまたはEdgeが見つかりません")
}

func chromiumCandidates() []string {
	if runtime.GOOS != "windows" {
		return nil
	}
	local := os.Getenv("LOCALAPPDATA")
	programFiles := os.Getenv("ProgramFiles")
	programFilesX86 := os.Getenv("ProgramFiles(x86)")
	return []string{
		filepath.Join(programFiles, "Microsoft", "Edge", "Application", "msedge.exe"),
		filepath.Join(programFilesX86, "Microsoft", "Edge", "Application", "msedge.exe"),
		filepath.Join(local, "Microsoft", "Edge", "Application", "msedge.exe"),
		filepath.Join(programFiles, "Google", "Chrome", "Application", "chrome.exe"),
		filepath.Join(programFilesX86, "Google", "Chrome", "Application", "chrome.exe"),
		filepath.Join(local, "Google", "Chrome", "Application", "chrome.exe"),
	}
}

func expectedAccept(key string) string {
	sum := sha1.Sum([]byte(key + "258EAFA5-E914-47DA-95CA-C5AB0DC85B11"))
	return base64.StdEncoding.EncodeToString(sum[:])
}
