package server

const dashboardCSSTokens = `
    @font-face {
      font-family: "Noto Sans JP";
      font-style: normal;
      font-weight: 400;
      font-display: swap;
      src: url("/assets/fonts/NotoSansJP-Regular.ttf") format("truetype");
    }
    @font-face {
      font-family: "Noto Sans JP";
      font-style: normal;
      font-weight: 500;
      font-display: swap;
      src: url("/assets/fonts/NotoSansJP-Medium.ttf") format("truetype");
    }
    @font-face {
      font-family: "Noto Sans JP";
      font-style: normal;
      font-weight: 600 900;
      font-display: swap;
      src: url("/assets/fonts/NotoSansJP-SemiBold.ttf") format("truetype");
    }
    /* Color roles: BG=surfaces, default=text/chrome, positive=start/success, accent=selection/connection/steps, negative=destructive/error. */
    :root {
      color-scheme: light;
      --color-bg: #f5f5f7;
      --color-default: #1d1d1f;
      --color-positive: #34c759;
      --color-accent: #007aff;
      --color-negative: #ff3b30;
      --color-white: #ffffff;
      --color-black: #000000;
      --surface: color-mix(in srgb, var(--color-bg) 12%, var(--color-white));
      --surface-raised: color-mix(in srgb, var(--color-bg) 5%, var(--color-white));
      --surface-muted: color-mix(in srgb, var(--color-bg) 88%, var(--color-default));
      --surface-strong: color-mix(in srgb, var(--color-bg) 72%, var(--color-default));
      --text-muted: color-mix(in srgb, var(--color-default) 62%, var(--color-bg));
      --border: color-mix(in srgb, var(--color-default) 17%, var(--color-bg));
      --border-strong: color-mix(in srgb, var(--color-default) 28%, var(--color-bg));
      --positive-soft: color-mix(in srgb, var(--color-positive) 14%, var(--surface));
      --accent-soft: color-mix(in srgb, var(--color-accent) 12%, var(--surface));
      --negative-soft: color-mix(in srgb, var(--color-negative) 14%, var(--surface));
      --on-positive: var(--color-white);
      --on-accent: var(--color-white);
      --on-negative: var(--color-white);
      --on-header: var(--color-white);
      --scrim: color-mix(in srgb, var(--color-default) 46%, transparent);
      --scrim-strong: color-mix(in srgb, var(--color-default) 58%, transparent);
      --media-black: var(--color-black);
      --bg: var(--color-bg);
      --panel: var(--surface);
      --panel-strong: var(--surface-raised);
      --ink: var(--color-default);
      --muted: var(--text-muted);
      --line: var(--border);
      --accent: var(--color-positive);
      --accent-blue: var(--color-accent);
      --accent-2: var(--color-negative);
      --soft: var(--positive-soft);
      --soft-blue: var(--accent-soft);
      --header-bg: linear-gradient(135deg, var(--color-default) 0%, color-mix(in srgb, var(--color-default) 80%, var(--color-accent)) 58%, var(--color-positive) 100%);
      --body-wash: linear-gradient(180deg, color-mix(in srgb, var(--color-accent) 7%, transparent), transparent 240px);
      --section-head-bg: linear-gradient(180deg, var(--surface), var(--surface-raised));
      --flow-primary-bg: linear-gradient(180deg, color-mix(in srgb, var(--color-accent) 6%, transparent), transparent 42%), var(--surface);
      --flow-secondary-bg: var(--color-bg);
      --control-bg: color-mix(in srgb, var(--color-bg) 82%, var(--color-default));
      --control-bg-strong: color-mix(in srgb, var(--color-bg) 72%, var(--color-default));
      --control-ink: color-mix(in srgb, var(--color-default) 86%, var(--color-bg));
      --control-active-bg: var(--color-default);
      --control-active-ink: var(--color-white);
      --tab-active-bg: var(--color-accent);
      --tab-active-ink: var(--on-accent);
      --switch-active-bg: var(--color-accent);
      --step-bg: var(--color-default);
      --step-ink: var(--color-white);
      --url-ink: var(--color-default);
      --preview-bg: var(--color-bg);
      --preview-check: color-mix(in srgb, var(--border) 48%, transparent);
      --danger: var(--color-negative);
      --success: var(--color-positive);
      --warning: color-mix(in srgb, var(--color-positive) 55%, var(--color-negative));
      --disabled-bg: color-mix(in srgb, var(--color-default) 34%, var(--color-bg));
      --radius-xs: 6px;
      --radius-small: 8px;
      --radius-control: 10px;
      --radius-card: 12px;
      --radius-panel: 14px;
      --radius-overlay: 16px;
      --radius-pill: 999px;
      --shadow-surface: 0 1px 0 color-mix(in srgb, var(--color-white) 72%, transparent) inset, 0 10px 24px color-mix(in srgb, var(--color-default) 8%, transparent);
      --shadow-surface-strong: 0 1px 0 color-mix(in srgb, var(--color-white) 78%, transparent) inset, 0 14px 34px color-mix(in srgb, var(--color-default) 9%, transparent);
      --shadow-overlay: 0 18px 42px color-mix(in srgb, var(--color-default) 22%, transparent);
      --shadow-control: 0 1px 2px color-mix(in srgb, var(--color-default) 8%, transparent);
      --shadow-control-hover: 0 4px 10px color-mix(in srgb, var(--color-default) 12%, transparent);
      --shadow-active: 0 2px 8px color-mix(in srgb, var(--color-default) 12%, transparent);
      --shadow-positive: 0 14px 28px color-mix(in srgb, var(--color-positive) 28%, transparent);
      --shadow-positive-soft: 0 16px 26px color-mix(in srgb, var(--color-positive) 24%, transparent);
      --shadow-inset-subtle: inset 0 1px 2px color-mix(in srgb, var(--color-default) 12%, transparent);
      --focus-ring: 0 0 0 3px color-mix(in srgb, var(--color-accent) 16%, transparent);
      --shadow: var(--shadow-surface);
      --shadow-soft: var(--shadow-control);
    }
    :root[data-theme="dark"] {
      color-scheme: dark;
      --color-bg: #000000;
      --color-default: #f5f5f7;
      --color-positive: #1f7a3b;
      --color-accent: #0a63c7;
      --color-negative: #d70015;
      --color-white: #ffffff;
      --color-black: #000000;
      --surface: color-mix(in srgb, var(--color-bg) 88%, var(--color-default));
      --surface-raised: color-mix(in srgb, var(--color-bg) 80%, var(--color-default));
      --surface-muted: color-mix(in srgb, var(--color-bg) 94%, var(--color-default));
      --surface-strong: color-mix(in srgb, var(--color-bg) 72%, var(--color-default));
      --text-muted: color-mix(in srgb, var(--color-default) 62%, var(--color-bg));
      --border: color-mix(in srgb, var(--color-default) 24%, var(--color-bg));
      --border-strong: color-mix(in srgb, var(--color-default) 34%, var(--color-bg));
      --positive-soft: color-mix(in srgb, var(--color-positive) 32%, var(--surface));
      --accent-soft: color-mix(in srgb, var(--color-accent) 32%, var(--surface));
      --negative-soft: color-mix(in srgb, var(--color-negative) 24%, var(--surface));
      --on-positive: var(--color-white);
      --on-accent: var(--color-white);
      --on-negative: var(--color-white);
      --on-header: var(--color-white);
      --scrim: color-mix(in srgb, var(--color-black) 54%, transparent);
      --scrim-strong: color-mix(in srgb, var(--color-black) 66%, transparent);
      --media-black: var(--color-black);
      --bg: var(--color-bg);
      --panel: var(--surface);
      --panel-strong: var(--surface-raised);
      --ink: var(--color-default);
      --muted: var(--text-muted);
      --line: var(--border);
      --accent: var(--color-positive);
      --accent-blue: var(--color-accent);
      --accent-2: var(--color-negative);
      --soft: var(--positive-soft);
      --soft-blue: var(--accent-soft);
      --header-bg: linear-gradient(135deg, var(--color-bg) 0%, var(--surface) 58%, var(--color-positive) 100%);
      --body-wash: linear-gradient(180deg, color-mix(in srgb, var(--color-accent) 13%, transparent), transparent 240px);
      --section-head-bg: linear-gradient(180deg, var(--surface-raised), var(--surface));
      --flow-primary-bg: linear-gradient(180deg, color-mix(in srgb, var(--color-accent) 10%, transparent), transparent 42%), var(--surface);
      --flow-secondary-bg: var(--surface-muted);
      --control-bg: var(--surface-raised);
      --control-bg-strong: var(--surface-strong);
      --control-ink: var(--color-default);
      --control-active-bg: var(--color-default);
      --control-active-ink: var(--color-bg);
      --tab-active-bg: var(--color-accent);
      --tab-active-ink: var(--on-accent);
      --switch-active-bg: var(--color-accent);
      --step-bg: var(--color-default);
      --step-ink: var(--color-bg);
      --url-ink: var(--color-default);
      --preview-bg: var(--surface-muted);
      --preview-check: color-mix(in srgb, var(--border) 42%, transparent);
      --danger: var(--color-negative);
      --success: var(--color-positive);
      --warning: color-mix(in srgb, var(--color-positive) 48%, var(--color-negative));
      --disabled-bg: color-mix(in srgb, var(--color-default) 38%, var(--color-bg));
      --shadow-surface: 0 1px 0 color-mix(in srgb, var(--color-white) 5%, transparent) inset, 0 14px 30px color-mix(in srgb, var(--color-black) 34%, transparent);
      --shadow-surface-strong: 0 1px 0 color-mix(in srgb, var(--color-white) 6%, transparent) inset, 0 18px 42px color-mix(in srgb, var(--color-black) 42%, transparent);
      --shadow-overlay: 0 22px 54px color-mix(in srgb, var(--color-black) 55%, transparent);
      --shadow-control: 0 1px 2px color-mix(in srgb, var(--color-black) 28%, transparent);
      --shadow-control-hover: 0 5px 14px color-mix(in srgb, var(--color-black) 36%, transparent);
      --shadow-active: 0 2px 10px color-mix(in srgb, var(--color-black) 34%, transparent);
      --shadow-positive: 0 14px 28px color-mix(in srgb, var(--color-positive) 34%, transparent);
      --shadow-positive-soft: 0 16px 26px color-mix(in srgb, var(--color-positive) 30%, transparent);
      --shadow-inset-subtle: inset 0 1px 2px color-mix(in srgb, var(--color-black) 30%, transparent);
      --focus-ring: 0 0 0 3px color-mix(in srgb, var(--color-accent) 22%, transparent);
    }`
