package server

const dashboardScriptState = dashboardScriptDomRefs + dashboardScriptStateSync + dashboardScriptPreview + dashboardScriptPreviewController + dashboardScriptHistoryQueue + dashboardScriptHistoryController + dashboardScriptProgressStatus + dashboardScriptUploadState + dashboardScriptUploadController + dashboardScriptMusicController + dashboardScriptPlaylistController + dashboardScriptSettingsController
