package video

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"math"
)

// GlyphSyntheticEvidence describes one isolated glyph mask produced by the
// diagnostic shader sentinel. It is intentionally separate from production
// rendering and gives the parity gate a stable atlas-vs-frame contract.
type GlyphSyntheticEvidence struct {
	ID                string                          `json:"id"`
	CPUAlphaCoverage  int                             `json:"cpuAlphaCoverage"`
	GPUAlphaCoverage  int                             `json:"gpuAlphaCoverage"`
	CPUAlphaSHA256    string                          `json:"cpuAlphaSha256"`
	GPUAlphaSHA256    string                          `json:"gpuAlphaSha256"`
	CPUVisibleBounds  [4]int                          `json:"cpuVisibleBounds"`
	CPUScreenBounds   [4]int                          `json:"cpuScreenBounds"`
	GPUVisibleBounds  [4]int                          `json:"gpuVisibleBounds"`
	CPUScreenCoverage int                             `json:"cpuScreenCoverage"`
	GPUScreenCoverage int                             `json:"gpuScreenCoverage"`
	ScreenIoU         float64                         `json:"screenIou"`
	Thresholds        map[string]GlyphThresholdMetric `json:"thresholds,omitempty"`
}
type GlyphThresholdMetric struct {
	CPU          int     `json:"cpu"`
	GPU          int     `json:"gpu"`
	Intersection int     `json:"intersection"`
	Union        int     `json:"union"`
	IoU          float64 `json:"iou"`
}

func thresholdMaskStats(values []uint8, threshold uint8) int {
	n := 0
	for _, v := range values {
		if v >= threshold {
			n++
		}
	}
	return n
}

// CompareSyntheticGlyph compares the first expanded glyph against an isolated
// GPU frame. The frame is grayscale coverage with opaque alpha, generated by
// the reserved diagnostic sequence; no scene background is included.
func CompareSyntheticGlyph(atlas *GlyphAtlasMetadata, manifest GlyphInstanceManifest, frame GpuFrame, width, height uint32) GlyphSyntheticEvidence {
	e := GlyphSyntheticEvidence{}
	if atlas == nil || len(manifest.Instances) == 0 || width == 0 || height == 0 {
		return e
	}
	g := manifest.Instances[0]
	e.ID = g.ID
	sx0, sy0 := int(g.Screen[0]*float32(width)), int(g.Screen[1]*float32(height))
	sw, sh := int(g.Screen[2]*float32(width)), int(g.Screen[3]*float32(height))
	if sw < 1 {
		sw = 1
	}
	if sh < 1 {
		sh = 1
	}
	cpuScreenMask := make(map[int]struct{})
	cpuScreenMasks := make(map[uint8]map[int]struct{})
	for _, t := range []uint8{1, 8, 16, 32, 64, 128} {
		cpuScreenMasks[t] = make(map[int]struct{})
	}
	for i := range atlas.Glyphs {
		if atlas.Glyphs[i].ID == g.ID {
			a := atlas.Glyphs[i]
			h := sha256.Sum256(atlas.Payload)
			e.CPUAlphaSHA256 = hex.EncodeToString(h[:])
			for y := uint32(0); y < a.Height; y++ {
				for x := uint32(0); x < a.Width; x++ {
					off := int(y*atlas.RowStride + (a.X+x)*4 + 3)
					if off < len(atlas.Payload) {
						alpha := atlas.Payload[off]
						for threshold, mask := range cpuScreenMasks {
							if alpha >= threshold {
								if px := sx0 + int(float32(x)*float32(sw)/float32(a.Width)); px >= sx0 && px < sx0+sw {
									if py := sy0 + int(float32(y)*float32(sh)/float32(a.Height)); py >= sy0 && py < sy0+sh {
										mask[py*int(width)+px] = struct{}{}
									}
								}
							}
						}
						if alpha >= 8 {
							e.CPUAlphaCoverage++
						}
					}
				}
			}
			e.CPUVisibleBounds = [4]int{int(a.X), int(a.Y), int(a.X + a.Width), int(a.Y + a.Height)}
			break
		}
	}
	for p := range cpuScreenMasks[8] {
		cpuScreenMask[p] = struct{}{}
	}
	e.CPUScreenCoverage = len(cpuScreenMask)
	if len(cpuScreenMask) > 0 {
		minX, minY, maxX, maxY := int(width), int(height), -1, -1
		for p := range cpuScreenMask {
			x, y := p%int(width), p/int(width)
			minX, minY = minIntGlyph(minX, x), minIntGlyph(minY, y)
			maxX, maxY = maxIntGlyph(maxX, x), maxIntGlyph(maxY, y)
		}
		e.CPUScreenBounds = [4]int{minX, minY, maxX + 1, maxY + 1}
	}
	gpuScreenMask := make(map[int]struct{})
	gpuScreenMasks := make(map[uint8]map[int]struct{})
	for _, t := range []uint8{1, 8, 16, 32, 64, 128} {
		gpuScreenMasks[t] = make(map[int]struct{})
	}
	if len(frame.Payload) == 0 {
		return e
	}
	minX, minY, maxX, maxY := int(width), int(height), -1, -1
	var raw []byte
	for y := uint32(0); y < height; y++ {
		for x := uint32(0); x < width; x++ {
			off := int(y*frame.RowStride + x*4)
			if off+2 >= len(frame.Payload) {
				continue
			}
			v := frame.Payload[off]
			raw = append(raw, v)
			if v > 0 {
				e.GPUAlphaCoverage++
				if int(x) < minX {
					minX = int(x)
				}
				if int(y) < minY {
					minY = int(y)
				}
				if int(x) > maxX {
					maxX = int(x)
				}
				if int(y) > maxY {
					maxY = int(y)
				}
			}
			if int(x) >= sx0 && int(x) < sx0+sw && int(y) >= sy0 && int(y) < sy0+sh {
				for threshold, mask := range gpuScreenMasks {
					if v >= threshold {
						mask[int(y)*int(width)+int(x)] = struct{}{}
					}
				}
			}
		}
	}
	h := sha256.Sum256(raw)
	e.GPUAlphaSHA256 = hex.EncodeToString(h[:])
	if maxX >= 0 {
		e.GPUVisibleBounds = [4]int{minX, minY, maxX + 1, maxY + 1}
	}
	for p := range gpuScreenMasks[8] {
		gpuScreenMask[p] = struct{}{}
	}
	e.GPUScreenCoverage = len(gpuScreenMask)
	inter := 0
	for p := range cpuScreenMask {
		if _, ok := gpuScreenMask[p]; ok {
			inter++
		}
	}
	union := len(cpuScreenMask) + len(gpuScreenMask) - inter
	if union > 0 {
		e.ScreenIoU = float64(inter) / float64(union)
	}
	e.Thresholds = map[string]GlyphThresholdMetric{}
	for _, threshold := range []uint8{1, 8, 16, 32, 64, 128} {
		cm, gm := cpuScreenMasks[threshold], gpuScreenMasks[threshold]
		intersection := 0
		for p := range cm {
			if _, ok := gm[p]; ok {
				intersection++
			}
		}
		union := len(cm) + len(gm) - intersection
		metric := GlyphThresholdMetric{CPU: len(cm), GPU: len(gm), Intersection: intersection, Union: union}
		if union > 0 {
			metric.IoU = float64(intersection) / float64(union)
		}
		e.Thresholds[fmt.Sprintf("%d", threshold)] = metric
	}
	return e
}

func minIntGlyph(a, b int) int {
	if a < b {
		return a
	}
	return b
}
func maxIntGlyph(a, b int) int {
	if a > b {
		return a
	}
	return b
}

// ExpandMusicGlyphManifest applies the same bounded expansion contract as the
// GPU sidecar. Coordinates are normalized to the requested render target.
func ExpandMusicGlyphManifest(scene *MusicScenePayload, width, height uint32) GlyphInstanceManifest {
	m := GlyphInstanceManifest{}
	if scene == nil || scene.GlyphAtlas == nil || width == 0 || height == 0 {
		return m
	}
	a := scene.GlyphAtlas
	sx, sy := float32(width)/1280, float32(height)/720
	for _, run := range a.TextRuns {
		if len(m.Instances) >= 256 {
			break
		}
		cursor := run.X * sx
		for _, ch := range []rune(run.Text) {
			if len(m.Instances) >= 256 {
				break
			}
			id := musicGlyphID(run.FontWeight, ch)
			var g *GlyphEntry
			for i := range a.Glyphs {
				if a.Glyphs[i].ID == id {
					g = &a.Glyphs[i]
					break
				}
			}
			if g == nil {
				legacyID := string(ch)
				for i := range a.Glyphs {
					if a.Glyphs[i].ID == legacyID {
						g = &a.Glyphs[i]
						break
					}
				}
			}
			if g == nil {
				for i := range a.Glyphs {
					if a.Glyphs[i].ID == a.MissingGlyphID {
						g = &a.Glyphs[i]
						break
					}
				}
			}
			if g == nil {
				continue
			}
			const atlasFaceSize float32 = musicAtlasLayoutEm
			const atlasInkTop float32 = 7
			scale := run.SizePx / atlasFaceSize
			sw := float32(g.Width) * scale
			if sw < 1 {
				sw = 1
			}
			sh := float32(g.Height) * scale * sy
			if sh < 1 {
				sh = 1
			}
			screenY := run.Y - atlasInkTop*scale
			if screenY < 0 {
				screenY = 0
			}
			rgba := [4]float32{float32(run.RGBA[0]) / 255, float32(run.RGBA[1]) / 255, float32(run.RGBA[2]) / 255, float32(run.RGBA[3]) / 255 * clampGlyph(run.Opacity)}
			m.Instances = append(m.Instances, GlyphInstanceDiagnostic{
				ID: g.ID, Screen: [4]float32{cursor / float32(width), screenY * sy / float32(height), sw * sx / float32(width), sh / float32(height)},
				Atlas: [4]float32{float32(g.X) / float32(a.Width), float32(g.Y) / float32(a.Height), float32(g.Width) / float32(a.Width), float32(g.Height) / float32(a.Height)},
				Color: rgba, Scale: scale, Baseline: run.Y * sy, InkTop: atlasInkTop * scale * sy,
				CellPadding: [4]float32{maxf(0, 64-float32(g.Width)), maxf(0, 64-float32(g.Height)), 0, 0},
			})
			cursor += maxf(g.Advance, 1) * scale * sx
		}
	}
	m.Count = len(m.Instances)
	if b, err := json.Marshal(m.Instances); err == nil {
		h := sha256.Sum256(b)
		m.SHA256 = hex.EncodeToString(h[:])
	}
	return m
}

func clampGlyph(v float32) float32 {
	if v < 0 {
		return 0
	}
	if v > 1 {
		return 1
	}
	return v
}
func maxf(a, b float32) float32 {
	if a > b {
		return a
	}
	return b
}

// CompareMusicGlyphManifest compares sidecar readback values with a CPU
// manifest. It reports every positional/value mismatch, bounded to avoid huge
// diagnostics in a report.
func CompareMusicGlyphManifest(cpu GlyphInstanceManifest, gpu *GlyphRenderDiagnostics) GlyphInstanceParity {
	p := GlyphInstanceParity{CPUCount: cpu.Count}
	if gpu == nil {
		p.GPUCount = -1
		p.Mismatches = cpu.Count
		p.FirstMismatch = "missing GPU diagnostics"
		p.CPUManifestSHA = cpu.SHA256
		return p
	}
	p.GPUCount = gpu.Count
	p.CPUManifestSHA = cpu.SHA256
	if b, e := json.Marshal(gpu.Instances); e == nil {
		h := sha256.Sum256(b)
		p.GPUManifestSHA = hex.EncodeToString(h[:])
	}
	n := cpu.Count
	if gpu.Count < n {
		n = gpu.Count
	}
	p.Matched = n
	for i := 0; i < n; i++ {
		a, b := cpu.Instances[i], gpu.Instances[i]
		if a.ID != b.ID || !sameFloats(a.Screen, b.Screen) || !sameFloats(a.Atlas, b.Atlas) || !sameFloats(a.Color, b.Color) || !closeGlyph(a.Scale, b.Scale) || !closeGlyph(a.Baseline, b.Baseline) || !closeGlyph(a.InkTop, b.InkTop) || !sameFloats(a.CellPadding, b.CellPadding) {
			p.Mismatches++
			if p.FirstMismatch == "" {
				p.FirstMismatch = fmt.Sprintf("index=%d cpu=%s gpu=%s", i, a.ID, b.ID)
			}
		}
	}
	if cpu.Count != gpu.Count {
		p.Mismatches += int(math.Abs(float64(cpu.Count - gpu.Count)))
		if p.FirstMismatch == "" {
			p.FirstMismatch = fmt.Sprintf("count cpu=%d gpu=%d", cpu.Count, gpu.Count)
		}
	}
	return p
}
func closeGlyph(a, b float32) bool { return float32(math.Abs(float64(a-b))) <= 1e-5 }
func sameFloats(a, b [4]float32) bool {
	for i := range a {
		if !closeGlyph(a[i], b[i]) {
			return false
		}
	}
	return true
}
