package video

import (
	"bytes"
	"context"
	"fmt"
	"image"
	"image/color"
	"image/draw"
	"image/png"
	"io"
	"math"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strconv"
	"strings"
	"sync"
	"time"

	"imagepadserver/internal/appicon"

	xdraw "golang.org/x/image/draw"
	"golang.org/x/image/font"
	"golang.org/x/image/font/opentype"
	"golang.org/x/image/math/fixed"
)

// runFFmpegOnce runs a short one-shot ffmpeg command, folding stderr into the
// error on failure.
func runFFmpegOnce(ctx context.Context, ffmpeg string, args []string) error {
	cmd := exec.CommandContext(ctx, ffmpeg, args...)
	hideWindow(cmd)
	var stderr bytes.Buffer
	cmd.Stderr = &stderr
	untrack := TrackStartedFFmpeg(cmd)
	defer untrack()
	if err := cmd.Run(); err != nil {
		detail := stderr.String()
		if len(detail) > 400 {
			detail = detail[len(detail)-400:]
		}
		return fmt.Errorf("%w: %s", err, detail)
	}
	return nil
}

// radioEdgeFadeSeconds is the black fade burned into the start and end of
// every pre-rendered playlist track so track changes cross through black.
const radioEdgeFadeSeconds = 0.7

const radioFallbackFadeInSeconds = 1.6
const radioFallbackFrameRate = 30
const radioFallbackFadeOutSeconds = 1.0
const radioFallbackRetimingHoldSeconds = 0.5

// RadioTrackFileName is the on-disk name of a pre-rendered playlist track.
// MP4 keeps AAC global headers so downstream copy remuxes stay clean.
func RadioTrackFileName(trackID string) string {
	return "radio-track-" + trackID + ".mp4"
}

// RenderRadioTrack renders the audio visualizer for one playlist track into a
// single MP4 file (with black edge fades) and returns its absolute path. The
// heavy lifting is the same pipeline as RunAudioVisualizerHLS; only the
// output muxer and the edge fades differ. progress (nil ok) receives the
// render fraction (0..1).
func RenderRadioTrack(ctx context.Context, outDir, ffmpeg string, input AudioRenderInput, trackID string, preset QualityPreset, progress func(float64)) (string, error) {
	return renderRadioTrackCPU(ctx, outDir, ffmpeg, input, trackID, preset, progress)
}

// renderRadioTrackCPU is the production playlist renderer. It intentionally
// reuses the canonical CPU visualizer pipeline so the playlist path has the
// same base-artwork, dynamic-layer, ASS, encoder, and mux behavior as the
// established CPU reference path. GPU sidecar code remains diagnostic-only.
func renderRadioTrackCPU(ctx context.Context, outDir, ffmpeg string, input AudioRenderInput, trackID string, preset QualityPreset, progress func(float64)) (string, error) {
	if err := os.MkdirAll(outDir, 0755); err != nil {
		return "", fmt.Errorf("create CPU radio output directory: %w", err)
	}
	outPath := filepath.Join(outDir, RadioTrackFileName(trackID))
	buildArgs := func(assPath, fontDir string, mode *ForegroundMode, encoder VideoEncoderProfile) []string {
		recipe := NewRadioRenderRecipe(preset, encoder, audioLoudnormFilter(input.Kind), input.Analysis.Duration)
		recipe.SourcePath = input.SourcePath
		recipe.ASSPath = assPath
		recipe.FontDir = fontDir
		recipe.OutputPath = outPath
		return recipe.FFmpegArgs(mode)
	}
	cleanup := func() {
		_ = os.Remove(outPath)
	}
	if err := runAudioVisualizerEncode(ctx, outDir, ffmpeg, input, trackID, preset, EncoderLowLatency, buildArgs, cleanup, progress); err != nil {
		return "", fmt.Errorf("CPU radio render: %w", err)
	}
	return outPath, nil
}

// renderRadioTrackGPU feeds wgpu-produced RGBA frames directly to FFmpeg's
// existing H.264/AAC mux path. Audio remains the source file; visuals are
// generated by the sidecar at the render clock, so showwaves/showfreqs/ASS are
// not applied a second time.
func renderRadioTrackGPU(ctx context.Context, outDir, ffmpeg, sidecarExe string, input AudioRenderInput, trackID string, preset QualityPreset, progress func(float64)) (string, error) {
	if os.Getenv("IMAGEPAD_GPU_H264_REQUIRED") == "1" {
		return renderRadioTrackGPUDirectH264(ctx, outDir, ffmpeg, sidecarExe, input, trackID, preset, progress)
	}
	outPath := filepath.Join(outDir, RadioTrackFileName(trackID))
	width, height := radioFallbackOutputSize(preset)
	encoder := SelectVideoEncoder(ctx, ffmpeg, EncoderLowLatency)
	args := []string{"-hide_banner", "-loglevel", "error", "-f", "rawvideo", "-pix_fmt", "rgba", "-s", fmt.Sprintf("%dx%d", width, height), "-r", "30", "-i", "pipe:0", "-i", input.SourcePath, "-map", "0:v:0", "-map", "1:a:0", "-t", strconv.FormatFloat(input.Analysis.Duration, 'f', 3, 64)}
	args = append(args, encoder.FFmpegArgs(preset, "veryfast")...)
	args = append(args, "-c:a", "aac", "-ar", "48000", "-ac", "2", "-movflags", "+faststart", outPath)
	cmd := exec.CommandContext(ctx, ffmpeg, args...)
	hideWindow(cmd)
	inPipe, err := cmd.StdinPipe()
	if err != nil {
		return "", err
	}
	var stderr bytes.Buffer
	cmd.Stderr = &stderr
	if err := cmd.Start(); err != nil {
		return "", err
	}
	sidecar, err := StartSidecar(ctx, sidecarExe, "music-"+trackID)
	if err != nil {
		_ = cmd.Process.Kill()
		return "", fmt.Errorf("%w: start sidecar: %v", ErrGPURendererUnavailable, err)
	}
	defer sidecar.Close()
	if err := sidecar.Hello(ctx, "music-"+trackID); err != nil {
		_ = cmd.Process.Kill()
		return "", fmt.Errorf("%w: sidecar hello: %v", ErrGPURendererUnavailable, err)
	}
	sceneBuilder := NewCanonicalMusicSceneBuilder(input)
	frames := int(math.Ceil(input.Analysis.Duration * 30))
	if frames < 1 {
		frames = 1
	}
	for i := 0; i < frames; i++ {
		ptsNS := int64(float64(i) * float64(time.Second) / 30)
		scene := sceneBuilder.Scene(uint64(i), ptsNS)
		frame, err := sidecar.RenderScene(ctx, uint32(width), uint32(height), uint64(i), ptsNS, &scene)
		if err != nil {
			_ = cmd.Process.Kill()
			return "", fmt.Errorf("%w: render frame: %v", ErrGPURendererUnavailable, err)
		}
		packed, err := GPUFrameToPackedRGBA(frame)
		if err != nil {
			_ = cmd.Process.Kill()
			return "", fmt.Errorf("%w: pack frame: %v", ErrGPURendererUnavailable, err)
		}
		if _, err := inPipe.Write(packed); err != nil {
			_ = cmd.Process.Kill()
			return "", err
		}
		if progress != nil {
			progress(float64(i+1) / float64(frames))
		}
	}
	_ = inPipe.Close()
	if err := cmd.Wait(); err != nil {
		return "", fmt.Errorf("GPU radio render: %w: %s", err, trimOutput(stderr.Bytes()))
	}
	return outPath, nil
}

// renderRadioTrackGPUDirectH264 consumes compressed H.264 access units from
// the sidecar's D3D12/NVENC route and copy-muxes them with the source audio.
// This path is deliberately opt-in until the sidecar advertises the complete
// production contract. It never accepts a pixel frame and never falls back to
// RGBA, CPU YUV packing, or libx264.
func renderRadioTrackGPUDirectH264(ctx context.Context, outDir, ffmpeg, sidecarExe string, input AudioRenderInput, trackID string, preset QualityPreset, progress func(float64)) (string, error) {
	totalStarted := time.Now()
	if err := os.MkdirAll(outDir, 0755); err != nil {
		return "", fmt.Errorf("create direct H264 output directory: %w", err)
	}
	outPath := filepath.Join(outDir, RadioTrackFileName(trackID))
	width, height := radioFallbackOutputSize(preset)
	args := directH264MuxArgs(input.SourcePath, outPath, width, height, input.Analysis.Duration)
	cmd := exec.CommandContext(ctx, ffmpeg, args...)
	hideWindow(cmd)
	inPipe, err := cmd.StdinPipe()
	if err != nil {
		return "", err
	}
	var stderr bytes.Buffer
	cmd.Stderr = &stderr
	ffmpegStart := time.Now()
	if err := cmd.Start(); err != nil {
		return "", err
	}
	gpuStageLog("go_ffmpeg_start seconds=%.6f", time.Since(ffmpegStart).Seconds())
	sidecarStart := time.Now()
	sidecar, err := StartSidecar(ctx, sidecarExe, "music-h264-"+trackID)
	if err != nil {
		_ = cmd.Process.Kill()
		_ = cmd.Wait()
		return "", fmt.Errorf("%w: start direct H264 sidecar: %v", ErrGPURendererUnavailable, err)
	}
	gpuStageLog("go_sidecar_start seconds=%.6f", time.Since(sidecarStart).Seconds())
	defer sidecar.Close()
	helloStarted := time.Now()
	if err := sidecar.Hello(ctx, "music-h264-"+trackID); err != nil {
		_ = cmd.Process.Kill()
		_ = cmd.Wait()
		return "", fmt.Errorf("%w: direct H264 sidecar hello: %v", ErrGPURendererUnavailable, err)
	}
	gpuStageLog("go_sidecar_hello seconds=%.6f backend=%s", time.Since(helloStarted).Seconds(), sidecar.Diagnostics().Backend)
	if err := sidecar.RequireH264Output(); err != nil {
		_ = cmd.Process.Kill()
		_ = cmd.Wait()
		return "", fmt.Errorf("%w: direct H264 output required: %v", ErrGPURendererUnavailable, err)
	}
	timelineStarted := time.Now()
	assets, timeline, err := CompilePlaylistGPUTrack(input, trackID)
	if err != nil {
		_ = cmd.Process.Kill()
		_ = cmd.Wait()
		return "", fmt.Errorf("%w: compile playlist GPU timeline: %v", ErrGPURendererUnavailable, err)
	}
	gpuStageLog("go_playlist_timeline_compile seconds=%.6f assets_hash=%s timeline_hash=%s", time.Since(timelineStarted).Seconds(), assets.AssetsHash, timeline.TimelineHash)
	playlistTimelineMode := os.Getenv("IMAGEPAD_GPU_PLAYLIST_TIMELINE") == "1"
	if playlistTimelineMode {
		prepareStarted := time.Now()
		if err := sidecar.PreparePlaylistTrack(ctx, 1, assets, playlistGPUSurfaceWidth, playlistGPUSurfaceHeight, timeline.FPS); err != nil {
			_ = cmd.Process.Kill()
			_ = cmd.Wait()
			return "", fmt.Errorf("%w: prepare playlist GPU track: %v", ErrGPURendererUnavailable, err)
		}
		gpuStageLog("go_playlist_prepare_track seconds=%.6f", time.Since(prepareStarted).Seconds())
	}
	builderStarted := time.Now()
	var sceneBuilder *CanonicalMusicSceneBuilder
	if !playlistTimelineMode {
		sceneBuilder = NewCanonicalMusicSceneBuilder(input)
		gpuStageLog("go_scene_builder seconds=%.6f", time.Since(builderStarted).Seconds())
	}
	frames := int(timeline.FrameCount)
	if frames < 1 {
		return "", fmt.Errorf("%w: compiled playlist GPU timeline has no frames", ErrGPURendererUnavailable)
	}
	var sceneBuildTotal, rpcTotal, pipeWriteTotal time.Duration
	batchCount := 0
	var bitstreamBytes int64
	for i := 0; i < frames; {
		batchEnd := i + GPUH264MaxBatchFrames
		if batchEnd > frames {
			batchEnd = frames
		}
		rpcStarted := time.Now()
		var encoded []EncodedH264Frame
		if playlistTimelineMode {
			chunk := TimelineChunk{
				ScrollProfiles: timeline.ScrollProfiles,
				Frames:         append([]FrameDirective(nil), timeline.Frames[i:batchEnd]...),
			}
			encoded, err = sidecar.RenderPlaylistTimelineBatch(ctx, uint64(batchCount), 1, assets.AssetsHash, timeline.TimelineVersion, chunk, nil)
		} else {
			batch := make([]H264RenderBatchFrame, 0, batchEnd-i)
			for frameIndex := i; frameIndex < batchEnd; frameIndex++ {
				ptsNS := timeline.Frames[frameIndex].PTSNs
				sceneStarted := time.Now()
				scene := sceneBuilder.Scene(uint64(frameIndex), ptsNS)
				sceneBuildTotal += time.Since(sceneStarted)
				batch = append(batch, H264RenderBatchFrame{
					Sequence: uint64(frameIndex),
					PTSNS:    ptsNS,
					Scene:    &scene,
				})
			}
			encoded, err = sidecar.RenderSceneH264Batch(ctx, uint32(width), uint32(height), batch)
		}
		rpcTotal += time.Since(rpcStarted)
		if err != nil {
			_ = cmd.Process.Kill()
			return "", fmt.Errorf("%w: direct H264 batch starting frame %d: %v", ErrGPURendererUnavailable, i, err)
		}
		batchCount++
		for offset, frame := range encoded {
			frameIndex := i + offset
			pipeStarted := time.Now()
			if _, err := inPipe.Write(frame.Payload); err != nil {
				_ = inPipe.Close()
				waitErr := cmd.Wait()
				return "", fmt.Errorf("%w: write direct H264 frame %d: %v; ffmpeg_wait=%v; ffmpeg_stderr=%s", ErrGPURendererUnavailable, frameIndex, err, waitErr, trimOutput(stderr.Bytes()))
			}
			pipeWriteTotal += time.Since(pipeStarted)
			bitstreamBytes += int64(len(frame.Payload))
			if progress != nil {
				progress(float64(frameIndex+1) / float64(frames))
			}
		}
		i = batchEnd
	}
	flushStarted := time.Now()
	if err := sidecar.FlushH264(ctx); err != nil {
		_ = cmd.Process.Kill()
		_ = inPipe.Close()
		waitErr := cmd.Wait()
		return "", fmt.Errorf("%w: direct H264 flush: %v; ffmpeg_wait=%v; ffmpeg_stderr=%s", ErrGPURendererUnavailable, err, waitErr, trimOutput(stderr.Bytes()))
	}
	gpuStageLog("go_h264_flush seconds=%.6f", time.Since(flushStarted).Seconds())
	gpuStageLog("go_frame_totals frames=%d batches=%d batch_size_max=%d scene_build_seconds=%.6f rpc_seconds=%.6f pipe_write_seconds=%.6f bitstream_bytes=%d", frames, batchCount, GPUH264MaxBatchFrames, sceneBuildTotal.Seconds(), rpcTotal.Seconds(), pipeWriteTotal.Seconds(), bitstreamBytes)
	pipeCloseStarted := time.Now()
	if err := inPipe.Close(); err != nil {
		waitErr := cmd.Wait()
		return "", fmt.Errorf("close direct H264 pipe: %w; ffmpeg_wait=%v; ffmpeg_stderr=%s", err, waitErr, trimOutput(stderr.Bytes()))
	}
	gpuStageLog("go_ffmpeg_stdin_close seconds=%.6f", time.Since(pipeCloseStarted).Seconds())
	muxWaitStarted := time.Now()
	if err := cmd.Wait(); err != nil {
		return "", fmt.Errorf("direct H264 mux: %w: %s", err, trimOutput(stderr.Bytes()))
	}
	gpuStageLog("go_ffmpeg_mux_wait seconds=%.6f total_seconds=%.6f", time.Since(muxWaitStarted).Seconds(), time.Since(totalStarted).Seconds())
	return outPath, nil
}

func directH264MuxArgs(audioPath, outPath string, width, height int, duration float64) []string {
	args := []string{
		"-hide_banner", "-loglevel", "error",
		"-f", "h264",
		"-framerate", "30",
		"-i", "pipe:0",
		"-i", audioPath,
		"-map", "0:v:0",
		"-map", "1:a:0",
		"-c:v", "copy",
		"-c:a", "aac",
		"-ar", "48000",
		"-ac", "2",
		"-movflags", "+faststart",
	}
	if duration > 0 {
		args = append(args, "-t", strconv.FormatFloat(duration, 'f', 3, 64))
	}
	return append(args, outPath)
}

func audioVisualizerMP4ArgsWithEncoder(audioPath, assPath, fontDir, outPath string, preset QualityPreset, mode *ForegroundMode, encoder VideoEncoderProfile, audioFilter string, durationSeconds float64) []string {
	recipe := NewRadioRenderRecipe(preset, encoder, audioFilter, durationSeconds)
	recipe.SourcePath = audioPath
	recipe.ASSPath = assPath
	recipe.FontDir = fontDir
	recipe.OutputPath = outPath
	return recipe.FFmpegArgs(mode)
}

func radioRTSPVideoEncoderArgs(encoder VideoEncoderProfile, preset QualityPreset) []string {
	if encoder.Name == "" {
		encoder = CPUVideoEncoder(EncoderLowLatency)
	}
	if encoder.Hardware {
		return encoder.FFmpegArgs(preset, "veryfast")
	}
	args := []string{"-c:v", "libx264", "-preset", "ultrafast", "-pix_fmt", "yuv420p"}
	return append(args, hardwareTargetBitrate(preset)...)
}

func radioRTSPEncodeOptions(encoder VideoEncoderProfile) []string {
	return radioRTSPEncodeOptionsForMode(encoder, "rtsp-ultra")
}

func radioRTSPEncodeOptionsForMode(encoder VideoEncoderProfile, mode string) []string {
	gop := radioLatencyGOPFrames(mode)
	args := []string{
		"-g", gop,
		"-keyint_min", gop,
		"-bf", "0",
		"-force_key_frames", "expr:gte(t,n_forced*" + radioLatencyKeyframeSeconds(mode) + ")",
	}
	if !encoder.Hardware {
		args = append(args, "-sc_threshold", "0", "-x264-params", "aud=1:repeat-headers=1")
	}
	return args
}

// RadioProgramEncoderArgs accepts the program clock's raw 30 fps RGBA frames
// and 48 kHz stereo PCM, then emits one continuous AVPro-compatible MPEG-TS
// stream. Input order, not source media timestamps, defines output PTS.
func RadioProgramEncoderArgs(preset QualityPreset, encoder VideoEncoderProfile, width, height int, videoInput, audioInput string) []string {
	if encoder.Name == "" {
		encoder = CPUVideoEncoder(EncoderLowLatency)
	}
	if width <= 0 || height <= 0 {
		width, height = RadioFallbackRenderSize(preset)
	}
	audioBitrate := strings.TrimSpace(preset.AudioBitrate)
	if audioBitrate == "" {
		audioBitrate = "128k"
	}
	mode := strings.TrimSpace(preset.RadioLatency)
	if mode == "" {
		mode = "rtsp-ultra"
	}
	args := []string{
		"-hide_banner", "-loglevel", "warning",
		"-fflags", "+genpts",
		"-thread_queue_size", "16",
		"-f", "rawvideo",
		"-pixel_format", "rgba",
		"-video_size", fmt.Sprintf("%dx%d", width, height),
		"-framerate", "30",
		"-i", videoInput,
		"-thread_queue_size", "16",
		"-f", "s16le",
		"-ar", "48000",
		"-ac", "2",
		"-i", audioInput,
		"-map", "0:v:0",
		"-map", "1:a:0",
		"-fps_mode:v", "passthrough",
	}
	args = append(args, radioRTSPVideoEncoderArgs(encoder, preset)...)
	args = append(args, radioRTSPEncodeOptionsForMode(encoder, mode)...)
	return append(args,
		"-c:a", "aac",
		"-ar", "48000",
		"-ac", "2",
		"-b:a", audioBitrate,
		"-bsf:v", "h264_metadata=aud=insert,dump_extra=freq=keyframe",
		"-mpegts_flags", "+resend_headers",
		"-muxdelay", "0",
		"-f", "mpegts",
		"pipe:1",
	)
}

func radioLatencyGOPFrames(mode string) string {
	return strconv.Itoa(legacyRadioGOPFrames(mode))
}

func radioLatencyKeyframeSeconds(mode string) string {
	switch strings.ToLower(strings.TrimSpace(mode)) {
	case "rtsp-low":
		return "2"
	case "rtsp-realtime":
		return "0.5"
	default:
		return "1"
	}
}

// WriteRadioFallbackLogo writes the app logo used by the active standby feeder.
func WriteRadioFallbackLogo(outDir string) (string, error) {
	path := filepath.Join(outDir, "radio-fallback-logo.png")
	if stat, err := os.Stat(path); err == nil && stat.Size() > 0 {
		return path, nil
	}
	if err := os.WriteFile(path, appIconPNG(), 0600); err != nil {
		return "", err
	}
	return path, nil
}

func appIconPNG() []byte {
	return appicon.IconPNG
}

// WriteRadioFallbackPanels writes reusable translucent rounded panels for the
// active standby feeder. FFmpeg draws the animated layers live, while these
// small PNGs keep the rounded UI geometry precise without adding dependencies.
func WriteRadioFallbackPanels(outDir string) (string, string, error) {
	messagePath := filepath.Join(outDir, "radio-fallback-message-panel.png")
	iconPath := filepath.Join(outDir, "radio-fallback-icon-panel.png")
	if err := writeRoundedPanelIfMissing(messagePath, 572, 282, 36, color.RGBA{18, 29, 48, 118}, color.RGBA{158, 215, 255, 116}); err != nil {
		return "", "", err
	}
	if err := writeRoundedPanelIfMissing(iconPath, 288, 288, 38, color.RGBA{255, 255, 255, 12}, color.RGBA{255, 255, 255, 25}); err != nil {
		return "", "", err
	}
	return messagePath, iconPath, nil
}

func writeRoundedPanelIfMissing(path string, width, height, radius int, fill, stroke color.RGBA) error {
	if stat, err := os.Stat(path); err == nil && stat.Size() > 0 {
		return nil
	}
	img := image.NewRGBA(image.Rect(0, 0, width, height))
	for y := 0; y < height; y++ {
		for x := 0; x < width; x++ {
			if insideRoundedRect(x, y, width, height, radius) {
				img.SetRGBA(x, y, fill)
			}
		}
	}
	for y := 0; y < height; y++ {
		for x := 0; x < width; x++ {
			if insideRoundedRect(x, y, width, height, radius) && !insideRoundedRect(x-2, y-2, width-4, height-4, radius-2) {
				img.SetRGBA(x, y, stroke)
			}
		}
	}
	file, err := os.Create(path)
	if err != nil {
		return err
	}
	defer file.Close()
	return png.Encode(file, img)
}

func insideRoundedRect(x, y, width, height, radius int) bool {
	if width <= 0 || height <= 0 {
		return false
	}
	if radius <= 0 {
		return x >= 0 && y >= 0 && x < width && y < height
	}
	if x < 0 || y < 0 || x >= width || y >= height {
		return false
	}
	if x >= radius && x < width-radius {
		return true
	}
	if y >= radius && y < height-radius {
		return true
	}
	cx := radius - 1
	if x >= width-radius {
		cx = width - radius
	}
	cy := radius - 1
	if y >= height-radius {
		cy = height - radius
	}
	dx := x - cx
	dy := y - cy
	return dx*dx+dy*dy <= radius*radius
}

// RadioFallbackFeederArgs generates the standby screen live as MPEG-TS. It is
// intentionally not a looped MP4, so waiting streams stay visually active until
// a real track feeder takes over.
func RadioFallbackRenderSize(preset QualityPreset) (int, int) {
	_, outputHeight := radioFallbackOutputSize(preset)
	height := outputHeight
	if height > 360 {
		height = height * 3 / 4
	}
	if height < 360 {
		height = 360
	}
	if height%2 != 0 {
		height++
	}
	width := height * 16 / 9
	if width%2 != 0 {
		width++
	}
	return width, height
}

func radioFallbackOutputSize(preset QualityPreset) (int, int) {
	height := preset.Height
	if height <= 0 {
		height = 720
	}
	width := height * 16 / 9
	if width%2 != 0 {
		width++
	}
	return width, height
}

func RadioFallbackFeederArgs(preset QualityPreset, renderWidth, renderHeight int, timestampOffset float64) []string {
	return RadioFallbackFeederArgsWithEncoder(preset, renderWidth, renderHeight, timestampOffset, CPUVideoEncoder(EncoderLowLatency))
}

func RadioFallbackFeederArgsWithEncoder(preset QualityPreset, renderWidth, renderHeight int, timestampOffset float64, encoder VideoEncoderProfile) []string {
	if encoder.Name == "" {
		encoder = CPUVideoEncoder(EncoderLowLatency)
	}
	outputWidth, outputHeight := radioFallbackOutputSize(preset)
	if renderWidth <= 0 || renderHeight <= 0 {
		renderWidth, renderHeight = RadioFallbackRenderSize(preset)
	}
	audioBitrate := preset.AudioBitrate
	if audioBitrate == "" {
		audioBitrate = "128k"
	}
	args := []string{
		"-hide_banner", "-loglevel", "error",
		"-f", "rawvideo", "-pix_fmt", "rgba", "-s", fmt.Sprintf("%dx%d", renderWidth, renderHeight), "-r", "30", "-i", "pipe:0",
		"-f", "lavfi", "-i", "anullsrc=r=48000:cl=stereo",
		"-map", "0:v:0", "-map", "1:a:0",
	}
	if renderWidth != outputWidth || renderHeight != outputHeight {
		args = append(args, "-vf", fmt.Sprintf("scale=%d:%d:flags=bicubic", outputWidth, outputHeight))
	}
	videoBitrate, maxRate, bufferSize := radioFallbackVideoRate(preset, outputHeight)
	encoderPreset := preset
	encoderPreset.VideoBitrate = videoBitrate
	encoderPreset.MaxRate = maxRate
	encoderPreset.BufferSize = bufferSize
	args = append(args, radioRTSPVideoEncoderArgs(encoder, encoderPreset)...)
	args = append(args, radioRTSPEncodeOptionsForMode(encoder, preset.RadioLatency)...)
	args = append(args, "-c:a", "aac", "-b:a", audioBitrate, "-ar", "48000", "-ac", "2")
	if timestampOffset > 0 {
		args = append(args, "-output_ts_offset", strconv.FormatFloat(timestampOffset, 'f', 3, 64))
	}
	return append(args, "-flush_packets", "1", "-f", "mpegts", "pipe:1")
}

func radioFallbackVideoRate(preset QualityPreset, outputHeight int) (videoBitrate, maxRate, bufferSize string) {
	if preset.VideoBitrate != "" {
		return preset.VideoBitrate, preset.MaxRate, preset.BufferSize
	}
	if outputHeight >= 1080 {
		return "1800k", "2400k", "4200k"
	}
	if outputHeight >= 720 {
		return "900k", "1200k", "2200k"
	}
	return "350k", "500k", "900k"
}

type RadioFallbackRenderer struct {
	width, height int
	scale         float64
	logo          *image.RGBA
	semiBold      font.Face
	medium        font.Face
	cubes         []radioFallbackCube
	waves         []radioFallbackWave
	waveLevelMaps [6][512]uint8
	bgBaseRX      []float32
	bgBaseGY      []float32
	bgBaseBY      []float32
	bgSinRX       []float32
	bgCosRX       []float32
	bgSinRY       []float32
	bgCosRY       []float32
	bgSinGX       []float32
	bgCosGX       []float32
	bgSinBY       []float32
	bgCosBY       []float32
	background    *image.RGBA
	backgroundKey int
	staticLayer   *image.RGBA
	staticSpans   []radioFallbackStaticSpan
	frame         *image.RGBA
	rgb           []byte
	workers       int
}

type radioFallbackStaticSpan struct {
	y, x0, x1 int
}

type radioFallbackCube struct {
	x, y, size, ax, ay, fx, fy, phase float64
	alpha                             uint8
	col                               color.RGBA
}

type radioFallbackWave struct {
	base, amp, thick, speed, freq, phase float64
	col                                  color.RGBA
	lut                                  [2]radioFallbackWaveLUT
}

type radioFallbackWaveLUT struct {
	levels [8]radioFallbackBlendLUT
}

type radioFallbackBlendLUT struct {
	r, g, b [256]uint8
	alpha   uint8
}

// NewRadioFallbackRenderer creates the active standby renderer used by the
// playlist fallback stream. It intentionally shares the same visual constants
// as the approved v6 preview: centered logo/message layout, slow color drift,
// broad translucent wave sheets, and small drifting cube bubbles.
func NewRadioFallbackRenderer(width, height int, logoPath, semiboldFontPath, mediumFontPath string) (*RadioFallbackRenderer, error) {
	if width <= 0 || height <= 0 {
		return nil, fmt.Errorf("invalid fallback size %dx%d", width, height)
	}
	scale := float64(height) / 720.0
	logo, err := loadScaledFallbackLogo(logoPath, int(math.Round(240*scale)))
	if err != nil {
		return nil, err
	}
	semiBold, err := loadFallbackFontFace(semiboldFontPath, 39*scale)
	if err != nil {
		return nil, err
	}
	medium, err := loadFallbackFontFace(mediumFontPath, 23*scale)
	if err != nil {
		semiBold.Close()
		return nil, err
	}
	r := &RadioFallbackRenderer{
		width:    width,
		height:   height,
		scale:    scale,
		logo:     logo,
		semiBold: semiBold,
		medium:   medium,
		cubes:    fallbackCubes(width, height, scale),
		waves:    fallbackWaves(),
		workers:  fallbackWorkerCount(width, height),
	}
	r.precomputeBackground()
	r.background = image.NewRGBA(image.Rect(0, 0, width, height))
	r.backgroundKey = -1
	r.staticLayer = image.NewRGBA(image.Rect(0, 0, width, height))
	r.drawPanelsAndText(r.staticLayer)
	r.staticSpans = fallbackStaticSpans(r.staticLayer)
	r.frame = image.NewRGBA(image.Rect(0, 0, width, height))
	r.rgb = make([]byte, width*height*3)
	return r, nil
}

func loadScaledFallbackLogo(path string, size int) (*image.RGBA, error) {
	file, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer file.Close()
	src, _, err := image.Decode(file)
	if err != nil {
		return nil, err
	}
	dst := image.NewRGBA(image.Rect(0, 0, size, size))
	xdraw.CatmullRom.Scale(dst, dst.Bounds(), src, src.Bounds(), draw.Over, nil)
	return dst, nil
}

func loadFallbackFontFace(path string, size float64) (font.Face, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	parsed, err := opentype.Parse(data)
	if err != nil {
		return nil, err
	}
	return opentype.NewFace(parsed, &opentype.FaceOptions{Size: size, DPI: 72, Hinting: font.HintingFull})
}

func fallbackCubes(width, height int, scale float64) []radioFallbackCube {
	colors := []color.RGBA{
		{214, 247, 255, 255},
		{142, 231, 199, 255},
		{185, 199, 255, 255},
		{120, 210, 255, 255},
		{176, 245, 222, 255},
	}
	cubes := make([]radioFallbackCube, 0, 126)
	for i := 0; i < 126; i++ {
		cubes = append(cubes, radioFallbackCube{
			x:     float64(8 + (i*157)%max(16, width-16)),
			y:     float64(6 + (i*89)%max(12, height-12)),
			size:  float64(4+(i*7)%15) * scale,
			ax:    float64(10+(i*5)%33) * scale,
			ay:    float64(14+(i*11)%45) * scale,
			fx:    0.05 + float64(i%9)*0.014,
			fy:    0.07 + float64(i%7)*0.021,
			phase: float64(i) * 0.73,
			alpha: uint8(16 + (i*13)%29),
			col:   colors[i%len(colors)],
		})
	}
	return cubes
}

func fallbackWaves() []radioFallbackWave {
	waves := []radioFallbackWave{
		{base: 242, amp: 50, thick: 146, speed: 0.24, freq: 148, phase: 0.2, col: color.RGBA{82, 203, 255, 72}},
		{base: 360, amp: 68, thick: 184, speed: 0.17, freq: 190, phase: 1.85, col: color.RGBA{92, 241, 188, 66}},
		{base: 492, amp: 60, thick: 168, speed: 0.12, freq: 226, phase: 3.55, col: color.RGBA{172, 134, 255, 62}},
	}
	for i := range waves {
		waves[i].lut[0] = newRadioFallbackWaveLUT(waves[i].col)
		band2 := waves[i].col
		band2.A = uint8(float64(band2.A) * 0.70)
		waves[i].lut[1] = newRadioFallbackWaveLUT(band2)
	}
	return waves
}

func newRadioFallbackWaveLUT(col color.RGBA) radioFallbackWaveLUT {
	var waveLUT radioFallbackWaveLUT
	for i := range waveLUT.levels {
		// Smooth radial falloff: broad translucent edge, denser center.
		x := float64(i) / float64(len(waveLUT.levels)-1)
		falloff := 0.08 + 0.70*x*x*(3-2*x)
		level := col
		level.A = uint8(math.Round(float64(col.A) * falloff))
		waveLUT.levels[i] = newRadioFallbackBlendLUT(level)
	}
	return waveLUT
}

func newRadioFallbackBlendLUT(col color.RGBA) radioFallbackBlendLUT {
	var lut radioFallbackBlendLUT
	lut.alpha = col.A
	a := int(col.A)
	inv := 255 - a
	srcR := int(col.R) * a
	srcG := int(col.G) * a
	srcB := int(col.B) * a
	for i := 0; i < 256; i++ {
		lut.r[i] = uint8((srcR + i*inv) / 255)
		lut.g[i] = uint8((srcG + i*inv) / 255)
		lut.b[i] = uint8((srcB + i*inv) / 255)
	}
	return lut
}

func fallbackWorkerCount(width, height int) int {
	if width*height < 320*180 {
		return 1
	}
	n := runtime.GOMAXPROCS(0)
	if n > 6 {
		n = 6
	}
	if n < 1 {
		n = 1
	}
	return n
}

func (r *RadioFallbackRenderer) Close() error {
	if closer, ok := r.semiBold.(interface{ Close() error }); ok {
		_ = closer.Close()
	}
	if closer, ok := r.medium.(interface{ Close() error }); ok {
		_ = closer.Close()
	}
	return nil
}

func (r *RadioFallbackRenderer) RenderRGB(seconds float64) []byte {
	img := image.NewRGBA(image.Rect(0, 0, r.width, r.height))
	out := make([]byte, r.width*r.height*3)
	r.renderRGBInto(img, out, seconds)
	return out
}

func (r *RadioFallbackRenderer) RenderReusableRGB(seconds float64) []byte {
	r.renderRGBInto(r.frame, r.rgb, seconds)
	return r.rgb
}

func (r *RadioFallbackRenderer) RenderReusableRGBA(seconds float64) []byte {
	r.renderFrameInto(r.frame, seconds)
	return r.frame.Pix
}

func (r *RadioFallbackRenderer) renderRGBInto(img *image.RGBA, out []byte, seconds float64) {
	r.renderFrameInto(img, seconds)
	j := 0
	for y := 0; y < r.height; y++ {
		row := img.Pix[y*img.Stride:]
		for x := 0; x < r.width; x++ {
			i := x * 4
			out[j+0] = row[i+0]
			out[j+1] = row[i+1]
			out[j+2] = row[i+2]
			j += 3
		}
	}
}

func (r *RadioFallbackRenderer) renderFrameInto(img *image.RGBA, seconds float64) {
	r.drawCachedBackground(img, seconds)
	r.drawCubes(img, seconds)
	r.drawStaticLayer(img)
	if seconds < radioFallbackFadeInSeconds {
		progress := seconds / radioFallbackFadeInSeconds
		eased := progress * progress * progress * (progress*(progress*6-15) + 10)
		a := uint8(math.Round(255 * (1 - eased)))
		alphaRect(img, image.Rect(0, 0, r.width, r.height), color.RGBA{0, 0, 0, a})
	}
}

func (r *RadioFallbackRenderer) drawCachedBackground(dst *image.RGBA, seconds float64) {
	key := int(seconds * 10)
	if key != r.backgroundKey {
		r.drawBackground(r.background, seconds)
		r.drawWaves(r.background, seconds)
		r.backgroundKey = key
	}
	copy(dst.Pix, r.background.Pix)
}

func fallbackStaticSpans(img *image.RGBA) []radioFallbackStaticSpan {
	spans := make([]radioFallbackStaticSpan, 0, img.Bounds().Dy())
	for y := 0; y < img.Bounds().Dy(); y++ {
		row := img.Pix[y*img.Stride:]
		x0 := -1
		x1 := -1
		for x := 0; x < img.Bounds().Dx(); x++ {
			if row[x*4+3] != 0 {
				if x0 < 0 {
					x0 = x
				}
				x1 = x + 1
			}
		}
		if x0 >= 0 {
			spans = append(spans, radioFallbackStaticSpan{y: y, x0: x0, x1: x1})
		}
	}
	return spans
}

func (r *RadioFallbackRenderer) drawStaticLayer(dst *image.RGBA) {
	for _, span := range r.staticSpans {
		dstRow := dst.Pix[span.y*dst.Stride:]
		srcRow := r.staticLayer.Pix[span.y*r.staticLayer.Stride:]
		for x := span.x0; x < span.x1; x++ {
			i := x * 4
			a := int(srcRow[i+3])
			if a == 0 {
				continue
			}
			inv := 255 - a
			dstRow[i+0] = uint8((int(srcRow[i+0])*a + int(dstRow[i+0])*inv) / 255)
			dstRow[i+1] = uint8((int(srcRow[i+1])*a + int(dstRow[i+1])*inv) / 255)
			dstRow[i+2] = uint8((int(srcRow[i+2])*a + int(dstRow[i+2])*inv) / 255)
			dstRow[i+3] = 255
		}
	}
}

func (r *RadioFallbackRenderer) drawBackground(img *image.RGBA, t float64) {
	baseR := float32(9 + 18*math.Sin(t*0.15))
	baseG := float32(21 + 20*math.Sin(t*0.11+1.6))
	baseB := float32(42 + 26*math.Sin(t*0.09+3.0))
	rSin := float32(math.Sin(t * 0.21))
	rCos := float32(math.Cos(t * 0.21))
	gSin := float32(math.Sin(t * 0.16))
	gCos := float32(math.Cos(t * 0.16))
	bSin := float32(math.Sin(t * 0.18))
	bCos := float32(math.Cos(t * 0.18))
	if r.workers <= 1 {
		r.drawBackgroundRows(img, 0, r.height, baseR, baseG, baseB, rSin, rCos, gSin, gCos, bSin, bCos)
		return
	}
	var wg sync.WaitGroup
	for w := 0; w < r.workers; w++ {
		y0 := r.height * w / r.workers
		y1 := r.height * (w + 1) / r.workers
		wg.Add(1)
		go func() {
			defer wg.Done()
			r.drawBackgroundRows(img, y0, y1, baseR, baseG, baseB, rSin, rCos, gSin, gCos, bSin, bCos)
		}()
	}
	wg.Wait()
}

func (r *RadioFallbackRenderer) drawBackgroundRows(img *image.RGBA, y0, y1 int, baseR, baseG, baseB, rSin, rCos, gSin, gCos, bSin, bCos float32) {
	for y := y0; y < y1; y += 2 {
		row := img.Pix[y*img.Stride:]
		var nextRow []byte
		if y+1 < y1 {
			nextRow = img.Pix[(y+1)*img.Stride:]
		}
		baseGY := r.bgBaseGY[y]
		baseBY := r.bgBaseBY[y]
		sinRY := r.bgSinRY[y]
		cosRY := r.bgCosRY[y]
		bvY := baseB + baseBY + 10*(r.bgSinBY[y]*bCos+r.bgCosBY[y]*bSin)
		for x := 0; x < r.width; x += 2 {
			p := x * 4
			sinR := r.bgSinRX[x]*cosRY + r.bgCosRX[x]*sinRY
			cosR := r.bgCosRX[x]*cosRY - r.bgSinRX[x]*sinRY
			rv := baseR + r.bgBaseRX[x] + 8*(sinR*rCos+cosR*rSin)
			gv := baseG + baseGY + 8*(r.bgSinGX[x]*gCos+r.bgCosGX[x]*gSin)
			rr := fallbackClampByte32(rv)
			gg := fallbackClampByte32(gv)
			bb := fallbackClampByte32(bvY)
			fillBackgroundPixel(row, p, rr, gg, bb)
			if x+1 < r.width {
				fillBackgroundPixel(row, p+4, rr, gg, bb)
			}
			if nextRow != nil {
				fillBackgroundPixel(nextRow, p, rr, gg, bb)
				if x+1 < r.width {
					fillBackgroundPixel(nextRow, p+4, rr, gg, bb)
				}
			}
		}
	}
}

func fillBackgroundPixel(row []byte, p int, rr, gg, bb uint8) {
	row[p+0] = rr
	row[p+1] = gg
	row[p+2] = bb
	row[p+3] = 255
}

func (r *RadioFallbackRenderer) precomputeBackground() {
	r.bgBaseRX = make([]float32, r.width)
	r.bgSinRX = make([]float32, r.width)
	r.bgCosRX = make([]float32, r.width)
	r.bgSinGX = make([]float32, r.width)
	r.bgCosGX = make([]float32, r.width)
	r.bgBaseGY = make([]float32, r.height)
	r.bgBaseBY = make([]float32, r.height)
	r.bgSinRY = make([]float32, r.height)
	r.bgCosRY = make([]float32, r.height)
	r.bgSinBY = make([]float32, r.height)
	r.bgCosBY = make([]float32, r.height)
	for x := 0; x < r.width; x++ {
		xn := float64(x) / float64(max(1, r.width))
		r.bgBaseRX[x] = float32(11 * xn)
		r.bgSinRX[x] = float32(math.Sin(xn * 5.2))
		r.bgCosRX[x] = float32(math.Cos(xn * 5.2))
		r.bgSinGX[x] = float32(math.Sin(xn * 6.8))
		r.bgCosGX[x] = float32(math.Cos(xn * 6.8))
	}
	for y := 0; y < r.height; y++ {
		yn := float64(y) / float64(max(1, r.height))
		r.bgBaseGY[y] = float32(15 * yn)
		r.bgBaseBY[y] = float32(19 * (1 - yn))
		r.bgSinRY[y] = float32(math.Sin(yn * 5.2))
		r.bgCosRY[y] = float32(math.Cos(yn * 5.2))
		r.bgSinBY[y] = float32(math.Sin(yn * 6.1))
		r.bgCosBY[y] = float32(math.Cos(yn * 6.1))
	}
}

func (r *RadioFallbackRenderer) drawWaves(img *image.RGBA, t float64) {
	for wi, wave := range r.waves {
		for band := 0; band < 2; band++ {
			thick := wave.thick * (0.72 + 0.26*math.Sin(t*(0.11+float64(wi)*0.04)+float64(band))) * r.scale
			breath := 1.0 + 0.14*math.Sin(t*(0.13+float64(wi)*0.03)+float64(band)*2.0)
			phase := wave.phase + float64(band)*1.7
			r.drawWaveBand(img, &wave.lut[band], r.waveLevelMaps[wi*2+band][:], 0, r.width, wave.base, wave.amp, wave.freq, wave.speed, phase, breath, thick*1.42, t)
		}
	}
}

func (r *RadioFallbackRenderer) drawWaveBand(img *image.RGBA, lut *radioFallbackWaveLUT, levelBuf []uint8, x0, x1 int, base, amp, freq, speed, phase, breath, thick, t float64) {
	levelOf := radioFallbackWaveLevelMap(thick, len(lut.levels), levelBuf)
	if r.workers <= 1 || x1-x0 < 128 {
		r.drawWaveBandRange(img, lut, levelOf, x0, x1, base, amp, freq, speed, phase, breath, thick, t)
		return
	}
	var wg sync.WaitGroup
	for w := 0; w < r.workers; w++ {
		wx0 := x0 + (x1-x0)*w/r.workers
		wx1 := x0 + (x1-x0)*(w+1)/r.workers
		wg.Add(1)
		go func() {
			defer wg.Done()
			r.drawWaveBandRange(img, lut, levelOf, wx0, wx1, base, amp, freq, speed, phase, breath, thick, t)
		}()
	}
	wg.Wait()
}

func radioFallbackWaveLevelMap(thick float64, levels int, buf []uint8) []uint8 {
	span := int(math.Ceil(thick)) + 4
	if span < 1 {
		span = 1
	}
	if span > len(buf) {
		buf = make([]uint8, span)
	} else {
		buf = buf[:span]
	}
	levelMax := float64(levels - 1)
	denom := float64(max(1, span-1))
	for i := range buf {
		position := float64(i) / denom
		proximity := 1 - math.Abs(position*2-1)
		buf[i] = uint8(proximity * levelMax)
	}
	return buf
}

func (r *RadioFallbackRenderer) drawWaveBandRange(img *image.RGBA, lut *radioFallbackWaveLUT, levelOf []uint8, x0, x1 int, base, amp, freq, speed, phase, breath, thick, t float64) {
	height := img.Bounds().Dy()
	half := thick / 2
	if half <= 0 {
		return
	}
	for x := x0; x < x1; x++ {
		xf := float64(x)
		y := base*r.scale + amp*r.scale*math.Sin(xf/(freq*r.scale*breath)+t*speed+phase)
		y += 18 * r.scale * math.Sin(xf/(freq*r.scale*0.47)-t*speed*0.86+phase*0.4)
		y0 := int(y - half)
		y1 := int(y + half)
		levelOffset := 0
		if y0 < 0 {
			levelOffset = -y0
			y0 = 0
		}
		if y1 > height {
			y1 = height
		}
		if y1 <= y0 {
			continue
		}
		for yy := y0; yy < y1; yy++ {
			levelIndex := levelOffset + yy - y0
			if levelIndex >= len(levelOf) {
				levelIndex = len(levelOf) - 1
			}
			blend := &lut.levels[levelOf[levelIndex]]
			i := yy*img.Stride + x*4
			img.Pix[i+0] = blend.r[img.Pix[i+0]]
			img.Pix[i+1] = blend.g[img.Pix[i+1]]
			img.Pix[i+2] = blend.b[img.Pix[i+2]]
			img.Pix[i+3] = 255
		}
	}
}

func (r *RadioFallbackRenderer) drawCubes(img *image.RGBA, t float64) {
	for _, c := range r.cubes {
		cx, cy := radioFallbackCubePosition(c, t, r.width, r.height, r.scale)
		size := c.size * (0.76 + 0.34*math.Sin(t*0.68+c.phase))
		half := size / 2
		a := uint8(float64(c.alpha) * (0.70 + 0.30*math.Sin(t*0.74+c.phase)))
		col := c.col
		col.A = a
		alphaRect(img, image.Rect(int(cx-half), int(cy-half), int(cx+half), int(cy+half)), col)
	}
}

func radioFallbackCubePosition(c radioFallbackCube, t float64, width, height int, scale float64) (float64, float64) {
	_ = width
	cx := c.x + c.ax*math.Sin(t*c.fx+c.phase)
	margin := 36 * scale
	cycle := float64(height) + margin*2
	drift := math.Mod(t*4.4+c.phase*37, cycle)
	cy := c.y + c.ay*math.Cos(t*c.fy+c.phase*0.8) - drift
	if cy < -margin {
		cy += cycle
	}
	return cx, cy
}

func (r *RadioFallbackRenderer) drawPanelsAndText(img *image.RGBA) {
	cy := r.height / 2
	logoSize := r.logo.Bounds().Dx()
	logoX := int(math.Round(146 * r.scale))
	logoY := cy - logoSize/2 + int(math.Round(5*r.scale))
	iconPanel := image.Rect(logoX-int(math.Round(24*r.scale)), cy-int(math.Round(144*r.scale)), logoX-int(math.Round(24*r.scale))+int(math.Round(288*r.scale)), cy+int(math.Round(144*r.scale)))
	messagePanel := image.Rect(int(math.Round(588*r.scale)), cy-int(math.Round(141*r.scale)), int(math.Round((588+572)*r.scale)), cy+int(math.Round(141*r.scale)))
	r.drawStaticPanelGlow(img, iconPanel, color.RGBA{86, 226, 255, 255}, 58, 18)
	r.drawStaticPanelGlow(img, messagePanel, color.RGBA{102, 238, 206, 255}, 64, 16)
	r.drawStaticPanelGlow(img, messagePanel.Add(image.Pt(0, int(math.Round(34*r.scale)))), color.RGBA{156, 126, 255, 255}, 52, 9)
	alphaRoundedRect(img, iconPanel, int(math.Round(38*r.scale)), color.RGBA{235, 250, 255, 28}, color.RGBA{190, 245, 255, 54})
	draw.Draw(img, image.Rect(logoX, logoY, logoX+logoSize, logoY+logoSize), r.logo, image.Point{}, draw.Over)
	alphaRoundedRect(img, messagePanel, int(math.Round(36*r.scale)), color.RGBA{34, 55, 82, 108}, color.RGBA{158, 225, 255, 126})

	textX := messagePanel.Min.X + int(math.Round(50*r.scale))
	textCenter := messagePanel.Min.Y + messagePanel.Dy()/2
	lift := int(math.Round(14 * r.scale))
	drawText(img, r.semiBold, textX, textCenter-int(math.Round(91*r.scale))-lift, "ImagePadServer Playlist", color.RGBA{243, 248, 255, 246})
	drawText(img, r.semiBold, textX, textCenter-int(math.Round(28*r.scale))-lift, "配信待機中", color.RGBA{123, 240, 200, 250})
	drawText(img, r.medium, textX, textCenter+int(math.Round(29*r.scale))-lift, "曲を追加するか、再生を押すと始まります", color.RGBA{213, 225, 239, 228})
	drawText(img, r.medium, textX, textCenter+int(math.Round(76*r.scale))-lift, "RTSP / HLS ready", color.RGBA{159, 180, 200, 220})
}

func (r *RadioFallbackRenderer) drawStaticPanelGlow(img *image.RGBA, rect image.Rectangle, col color.RGBA, spread, alpha int) {
	steps := 9
	for i := steps; i >= 1; i-- {
		t := float64(i) / float64(steps)
		padX := int(math.Round(float64(spread) * r.scale * t))
		padY := int(math.Round(float64(spread) * r.scale * t * 0.72))
		glowRect := image.Rect(rect.Min.X-padX, rect.Min.Y-padY, rect.Max.X+padX, rect.Max.Y+padY)
		glow := col
		glow.A = uint8(math.Round(float64(alpha) * (1 - t) * (1 - t)))
		if glow.A == 0 {
			continue
		}
		alphaRoundedRect(img, glowRect, int(math.Round((36+float64(spread)*0.38*t)*r.scale)), glow, color.RGBA{})
	}
}

func WriteRadioFallbackFrames(ctx context.Context, out io.Writer, renderer *RadioFallbackRenderer) (int, error) {
	return WriteTimedRadioFallbackFrames(ctx, out, renderer.RenderReusableRGBA)
}

func WriteTimedRadioFallbackFrames(ctx context.Context, out io.Writer, renderFrame func(seconds float64) []byte) (int, error) {
	ticker := time.NewTicker(time.Second / radioFallbackFrameRate)
	defer ticker.Stop()
	frames := 0
	for {
		select {
		case <-ctx.Done():
			return writeRadioFallbackFadeOutFrames(out, renderFrame, frames)
		default:
		}
		frame := renderFrame(float64(frames) / radioFallbackFrameRate)
		if _, err := out.Write(frame); err != nil {
			if ctx.Err() != nil {
				return frames, nil
			}
			return frames, err
		}
		frames++
		select {
		case <-ctx.Done():
			return writeRadioFallbackFadeOutFrames(out, renderFrame, frames)
		case <-ticker.C:
		}
	}
}

func writeRadioFallbackFadeOutFrames(out io.Writer, renderFrame func(seconds float64) []byte, frames int) (int, error) {
	fadeFrames := int(math.Round(radioFallbackFadeOutSeconds * radioFallbackFrameRate))
	holdFrames := int(math.Round(radioFallbackRetimingHoldSeconds * radioFallbackFrameRate))
	tailFrames := fadeFrames + holdFrames
	ticker := time.NewTicker(time.Second / radioFallbackFrameRate)
	defer ticker.Stop()
	for i := 0; i < fadeFrames; i++ {
		frame := renderFrame(float64(frames) / radioFallbackFrameRate)
		blackFadeRGBA(frame, smootherstep(float64(i+1)/float64(fadeFrames)))
		if _, err := out.Write(frame); err != nil {
			return frames, err
		}
		frames++
		if i+1 < tailFrames {
			<-ticker.C
		}
	}
	for i := 0; i < holdFrames; i++ {
		frame := renderFrame(float64(frames) / radioFallbackFrameRate)
		blackFadeRGBA(frame, 1)
		if _, err := out.Write(frame); err != nil {
			return frames, err
		}
		frames++
		if fadeFrames+i+1 < tailFrames {
			<-ticker.C
		}
	}
	return frames, nil
}

func smootherstep(x float64) float64 {
	if x <= 0 {
		return 0
	}
	if x >= 1 {
		return 1
	}
	return x * x * x * (x*(x*6-15) + 10)
}

func blackFadeRGBA(frame []byte, amount float64) {
	if amount <= 0 {
		return
	}
	if amount > 1 {
		amount = 1
	}
	keep := 1 - amount
	for i := 0; i+3 < len(frame); i += 4 {
		frame[i+0] = uint8(float64(frame[i+0]) * keep)
		frame[i+1] = uint8(float64(frame[i+1]) * keep)
		frame[i+2] = uint8(float64(frame[i+2]) * keep)
	}
}

func drawText(img *image.RGBA, face font.Face, x, y int, text string, col color.RGBA) {
	d := &font.Drawer{
		Dst:  img,
		Src:  image.NewUniform(col),
		Face: face,
		Dot:  fixed.P(x, y+face.Metrics().Ascent.Ceil()),
	}
	d.DrawString(text)
}

func alphaRoundedRect(img *image.RGBA, rect image.Rectangle, radius int, fill, stroke color.RGBA) {
	for y := rect.Min.Y; y < rect.Max.Y; y++ {
		for x := rect.Min.X; x < rect.Max.X; x++ {
			localX := x - rect.Min.X
			localY := y - rect.Min.Y
			if insideRoundedRect(localX, localY, rect.Dx(), rect.Dy(), radius) {
				alphaPixel(img, x, y, fill)
				if !insideRoundedRect(localX-2, localY-2, rect.Dx()-4, rect.Dy()-4, radius-2) {
					alphaPixel(img, x, y, stroke)
				}
			}
		}
	}
}

func alphaRect(img *image.RGBA, rect image.Rectangle, col color.RGBA) {
	rect = rect.Intersect(img.Bounds())
	if rect.Empty() || col.A == 0 {
		return
	}
	a := int(col.A)
	inv := 255 - a
	srcR := int(col.R) * a
	srcG := int(col.G) * a
	srcB := int(col.B) * a
	for y := rect.Min.Y; y < rect.Max.Y; y++ {
		row := img.Pix[y*img.Stride:]
		for x := rect.Min.X; x < rect.Max.X; x++ {
			i := x * 4
			row[i+0] = uint8((srcR + int(row[i+0])*inv) / 255)
			row[i+1] = uint8((srcG + int(row[i+1])*inv) / 255)
			row[i+2] = uint8((srcB + int(row[i+2])*inv) / 255)
			row[i+3] = 255
		}
	}
}

func alphaVLine(img *image.RGBA, x, y0, y1 int, col color.RGBA) {
	if x < 0 || x >= img.Bounds().Dx() || col.A == 0 {
		return
	}
	if y0 < 0 {
		y0 = 0
	}
	if y1 > img.Bounds().Dy() {
		y1 = img.Bounds().Dy()
	}
	if y1 <= y0 {
		return
	}
	a := int(col.A)
	inv := 255 - a
	srcR := int(col.R) * a
	srcG := int(col.G) * a
	srcB := int(col.B) * a
	for y := y0; y < y1; y++ {
		i := y*img.Stride + x*4
		img.Pix[i+0] = uint8((srcR + int(img.Pix[i+0])*inv) / 255)
		img.Pix[i+1] = uint8((srcG + int(img.Pix[i+1])*inv) / 255)
		img.Pix[i+2] = uint8((srcB + int(img.Pix[i+2])*inv) / 255)
		img.Pix[i+3] = 255
	}
}

func alphaPixel(img *image.RGBA, x, y int, src color.RGBA) {
	if !image.Pt(x, y).In(img.Bounds()) || src.A == 0 {
		return
	}
	i := img.PixOffset(x, y)
	sa := int(src.A)
	da := int(img.Pix[i+3])
	outA := sa + da*(255-sa)/255
	if outA <= 0 {
		img.Pix[i+0] = 0
		img.Pix[i+1] = 0
		img.Pix[i+2] = 0
		img.Pix[i+3] = 0
		return
	}
	srcR := int(src.R) * sa
	srcG := int(src.G) * sa
	srcB := int(src.B) * sa
	dstFactor := da * (255 - sa) / 255
	img.Pix[i+0] = uint8((srcR + int(img.Pix[i+0])*dstFactor) / outA)
	img.Pix[i+1] = uint8((srcG + int(img.Pix[i+1])*dstFactor) / outA)
	img.Pix[i+2] = uint8((srcB + int(img.Pix[i+2])*dstFactor) / outA)
	img.Pix[i+3] = uint8(outA)
}

func scaleRect(x0, y0, x1, y1 int, scale float64) image.Rectangle {
	return image.Rect(
		int(math.Round(float64(x0)*scale)),
		int(math.Round(float64(y0)*scale)),
		int(math.Round(float64(x1)*scale)),
		int(math.Round(float64(y1)*scale)),
	)
}

func fallbackClampByte(v float64) uint8 {
	if v <= 0 {
		return 0
	}
	if v >= 255 {
		return 255
	}
	return uint8(math.Round(v))
}

func fallbackClampByte32(v float32) uint8 {
	if v <= 0 {
		return 0
	}
	if v >= 255 {
		return 255
	}
	return uint8(v + 0.5)
}

// RadioPublisherArgs is the persistent RTSP publisher: it consumes an
// endless MPEG-TS byte stream on stdin and republishes it to MediaMTX. The
// feeder side is responsible for making per-segment timestamps monotonic; the
// publisher must preserve those PTS values so frame pacing is not derived from
// pipe arrival timing.
//
// Compatibility guardrail: keep the radio track/fallback feeders responsible
// for producing AAC at the shared radio parameters, and keep the publisher as a
// copy remuxer. Re-encoding audio here adds encoder delay across the persistent
// radio stream and can desynchronize playlist audio from the visualizer video.
func RadioPublisherArgs(rtspPublishURL string) []string {
	args := []string{
		"-hide_banner",
		"-loglevel", "warning",
		"-fflags", "+genpts",
		// The publisher consumes a persistent MPEG-TS pipe. Keep probing
		// bounded, but leave enough budget for PAT/PMT plus the first H.264
		// SPS/PPS/IDR access unit; a 32-byte/zero-duration probe cannot
		// discover the video dimensions on a live transport stream. Keep the
		// budget below the short evaluation segment so a persistent pipe does
		// not wait for an EOF that never arrives.
		"-thread_queue_size", "512",
		"-probesize", "16k",
		"-analyzeduration", "100000",
		"-fpsprobesize", "2",
		"-f", "mpegts",
		"-i", "pipe:0",
		"-c:v", "copy",
		"-c:a", "copy",
	}
	if strings.HasPrefix(strings.ToLower(strings.TrimSpace(rtspPublishURL)), "rtmp://") {
		return append(args,
			"-f", "flv",
			rtspPublishURL,
		)
	}
	return append(args,
		"-rtsp_transport", "tcp",
		"-pkt_size", "1200",
		"-muxdelay", "0",
		"-f", "rtsp",
		rtspPublishURL,
	)
}

// RadioFeederArgs converts one pre-rendered MP4 into a real-time MPEG-TS
// stream on stdout, for piping into the persistent publisher. loop repeats
// the input forever (filler); startSeconds resumes mid-track. timestampOffset
// shifts output PTS so separately started feeders form one monotonic stream.
//
// Compatibility guardrail: do not transcode here. This process is only the
// paced MP4-to-TS feeder; changing it to encode audio/video changes the byte
// stream seen by the persistent RTSP publisher and can make VRChat reject the
// stream before playback.
func RadioFeederArgs(mediaPath string, startSeconds int, loop bool, timestampOffset float64) []string {
	args := []string{
		"-hide_banner",
		"-loglevel", "error",
		"-re",
	}
	if loop {
		args = append(args, "-stream_loop", "-1")
	}
	if startSeconds > 0 {
		args = append(args, "-ss", strconv.Itoa(startSeconds))
	}
	args = append(args,
		"-i", mediaPath,
		"-c", "copy",
	)
	if timestampOffset > 0 {
		args = append(args, "-output_ts_offset", strconv.FormatFloat(timestampOffset, 'f', 3, 64))
	}
	return append(args,
		"-f", "mpegts",
		"pipe:1",
	)
}
