[package]
name = "nico-compositord"
version = "0.1.0"
edition = "2021"
license = "MIT"

[lib]
name = "nico_compositord"
path = "src/lib.rs"

[[bin]]
name = "nico-compositord"
path = "src/main.rs"

[dependencies]
bytemuck = { version = "1", features = ["derive"] }
pollster = "0.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"
wgpu = "=0.20.1"

[profile.release-thin]
inherits = "release"
lto = "thin"

[profile.release-thin-one]
inherits = "release-thin"
codegen-units = 1
